/**
 * 页面名称。需要对应resources/base/profile/route_map.json内的name。
 */
export enum PageNameEnum {
  ThreadPostList = 'ThreadPostList',
  UserSpace = 'UserSpace',
  Preferences = 'Preferences',
  ViewHistory = 'ViewHistory',
  FavoriteList = 'FavoriteList',
  PostRatingDetail = 'PostRatingDetail',
  PollDetail = "PollDetail",
  WriteReply = 'WriteReply',
  SearchPage = "SearchPage",
  UserThread = "UserThread",
  DraftPage = "DraftPage",
  PrivateMessage = "PrivateMessage",
  PmDetail = "PmDetail",
  NoteList = "NoteList",
  BlockList = "BlockList",
  AboutApp = "AboutApp",
  SplitModeShortcut = "SplitModeShortcut",
  UserGuide = "UserGuide",
  ReportPost = "ReportPost"
}